// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD02vqSTQUC-r3gedcZOD-mzJluNVtO1j8',
    appId: '1:56692159657:web:99d1c7c59b31a6975ba5b8',
    messagingSenderId: '56692159657',
    projectId: 'projappflutter',
    authDomain: 'projappflutter.firebaseapp.com',
    databaseURL: 'https://projappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'projappflutter.appspot.com',
    measurementId: 'G-KK7WLB46G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfOxpN6ZAAv8CuCWbS8pXXk4qoWNYWP4',
    appId: '1:56692159657:android:5cd013ac7e8341945ba5b8',
    messagingSenderId: '56692159657',
    projectId: 'projappflutter',
    databaseURL: 'https://projappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'projappflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHktStO3yOsV2Ffo5noFNVr9zQ1selyu4',
    appId: '1:56692159657:ios:d0c8af2d9d9a82d65ba5b8',
    messagingSenderId: '56692159657',
    projectId: 'projappflutter',
    databaseURL: 'https://projappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'projappflutter.appspot.com',
    iosClientId: '56692159657-edvfu0m9ap55ppu88g1j72f54ao7jo2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHktStO3yOsV2Ffo5noFNVr9zQ1selyu4',
    appId: '1:56692159657:ios:d0c8af2d9d9a82d65ba5b8',
    messagingSenderId: '56692159657',
    projectId: 'projappflutter',
    databaseURL: 'https://projappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'projappflutter.appspot.com',
    iosClientId: '56692159657-edvfu0m9ap55ppu88g1j72f54ao7jo2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter',
  );
}
